import json

rename_mapping = {
    'PRODUCT_NAME': 'PRODUCT_name',
    'PRODUCT_IMAGE': 'PRODUCT_image',
    'PRODUCT_NUMBER': 'PRODUCT_id',
    'DESCRIPTION': 'PRODUCT_description',
    'LANGUAGE': 'PRODUCT_LANGUAGE_name',
    'PRODUCTION_COST': 'PRODUCT_PRODUCTION_COST_money',
    'MARGIN': 'PRODUCT_MARGIN_percentage',
    'INTRODUCTION_DATE': 'PRODUCT_INTRODUCTION_DATE_date',
    'PRODUCT_LINE_CODE': 'PRODUCT_LINE_code',
    'PRODUCT_LINE_EN': 'PRODUCT_LINE_name',
    'PRODUCT_NUMBER': 'PRODUCT_id',
    'DESCRIPTION': 'PRODUCT_description',
    'LANGUAGE': 'PRODUCT_LANGUAGE_name',
    'PRODUCTION_COST': 'PRODUCT_PRODUCTION_COST_money',
    'MARGIN': 'PRODUCT_MARGIN_percentage',
    'INTRODUCTION_DATE': 'PRODUCT_INTRODUCTION_DATE_date',
    'PRODUCT_LINE_CODE': 'PRODUCT_LINE_code',
    'PRODUCT_LINE_EN': 'PRODUCT_LINE_name',
    'SALES_STAFF_CODE': 'SALES_STAFF_code', 
    'FIRST_NAME': 'FIRST_NAME_name', 
    'LAST_NAME': 'LAST_NAME_name', 
    'POSITION_EN' : 'POSITION_name',
    'WORK_PHONE': 'WORK_PHONE_phone', 
    'EXTENSION': 'EXTENSION_number', 
    'FAX': 'FAX_phone', 
    'EMAIL': 'EMAIL_address', 
    'DATE_HIRED': 'DATE_HIRED_date',
    'SALES_BRANCH_CODE': 'SALES_BRANCH_code', 
    'MANAGER_CODE': "MANAGER_code", 
    'ADDRESS1': 'ADDRESS1_address',
    'ADDRESS2': 'ADDRESS2_address', 
    'CITY': 'CITY_name', 
    'REGION': 'REGION_name', 
    'POSTAL_ZONE': 'POSTAL_ZONE_code', 
    'COUNTRY_CODE': 'COUNTRY_code', 
    'COUNTRY_EN': 'COUNTRY_name', 
    'LANGUAGE' : 'LANGUAGE_name', 
    'CURRENCY_NAME': 'CURRENCY_name', 
    'FLAG_IMAGE': 'FLAG_image', 
    'SALES_TERRITORY_CODE': 'SALES_TERRITORY_code',
    'TERRITORY_NAME_EN': 'TERRITORY_name',
    'ORDER_NUMBER': 'ORDER_number', 
    'RETAILER_NAME': 'RETAILER_name',
    'RETAILER_CONTACT_CODE': 'RETAILER_CONTACT_id', 
    'SALES_STAFF_CODE': 'SALES_STAFF_code',
    'ORDER_DATE': 'ORDER_DATE_date', 
    'ORDER_METHOD_CODE': 'ORDER_METHOD_id', 
    'ORDER_METHOD_EN': 'ORDER_METHOD_name',
    'RETAILER_SITE_CODE': 'RETAILER_SITE_code', 
    'FIRST_NAME' : 'FIRST_NAME_name',
    'LAST_NAME': 'LAST_NAME_name', 
    'JOB_POSITION_EN' : 'JOB_POSITION_name',
    'EXTENSION': 'EXTENSION_number', 
    'E_MAIL': 'EMAIL_address', 
    'GENDER': 'GENDER_code', 
    'RETAILER_CODE': 'RETAILER_code',
    'CITY': 'CITY_name', 
    'REGION': 'REGION_name',
    'POSTAL_ZONE': 'POSTAL_ZONE_code', 
    'COUNTRY_CODE': 'COUNTRY_code', 
    'ACTIVE_INDICATOR': 'ACTIVE_INDICATOR_bool',
    'COUNTRY_EN': 'COUNTRY_name', 
    'LANGUAGE' : 'LANGUAGE_name', 
    'CURRENCY_NAME': 'CURRENCY_name', 
    'FLAG_IMAGE': 'FLAG_image', 
    'SALES_TERRITORY_CODE': 'SALES_TERRITORY_code',
    'TERRITORY_NAME_EN': 'TERRITORY_name',
    'SEGMENT_CODE': 'SEGMENT_code',
    'COMPANY_NAME': 'COMPANY_name',
    'RETAILER_TYPE_CODE': 'RETAILER_TYPE_code',
    'RETAILER_CODEMR': 'RETAILER_MR_code',
    'RETAILER_TYPE_EN': 'RETAILER_TYPE_name',
    'PHONE': 'PHONE_phone',
    'EXPECTED_VOLUME': 'EXPECTED_VOLUME_volume',
    'YEAR': 'YEAR_number',
    'MONTH': 'MONTH_number',
    'SATISFACTION_TYPE_DESCRIPTION': 'SATISFACTION_TYPE_description',
    'COURSE_DESCRIPTION': 'COURSE_description',
    'RETURN_DESCRIPTION_EN': 'RETURN_REASON_description',
    'ORDER_DETAIL_CODE': 'ORDER_DETAIL_code', 
    'RETURN_CODE': 'RETURN_code', 
    'RETURN_DATE': 'RETURN_DATE_date', 
    'RETURN_QUANTITY': 'RETURN_QUANTITY_number', 
    'RETURN_REASON_CODE': 'RETURN_REASON_code', 
    'QUANTITY' : 'QUANTITY_number',
    'UNIT_COST' : 'UNIT_COST_money', 
    'UNIT_PRICE' : 'UNIT_PRICE_money', 
    'UNIT_SALE_PRICE' : 'UNIT_SALE_PRICE_money', 
}

#print(sorted(rename_mapping))

print(str(json.dumps(rename_mapping, indent=4, sort_keys=True)).replace('\"', '\''))
